# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: pretty

# Setup
title: Steven Cho
tagline: "My Personal Website"
description: "Cooper Union for the Advancement of Science and Art '23"
url: https://joongyeoncho0823.github.io
baseurl: /

author:
  name: "Joongyeon Cho"
  url: "https://github.com/joongyeoncho0823"

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

# Custom vars
version: 2.1.0

github:
  repo: https://github.com/joongyeoncho0823/joongyeoncho0823.github.io
